// handlers_pdf_auto_shared.go — PDF 자동 생성 (Mac/Windows 공용)
// gofpdf 라이브러리 사용 (CGO 없음, Pure Go)
//
// 라우팅:
//   "PDF 보고서 만들어줘"   → format=pdf
//   "분기 매출 PDF 작성"    → topic 자동 추출
//   "create PDF report"     → 영어도 동등
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// cmdPdfAutoCreate: LLM 본문 생성 → PDF 저장 → 경로 응답
// params: { topic?, tone? }
func cmdPdfAutoCreate(params map[string]any, original, gKey, lang string) (result any, message string) {
	topic, _ := params["topic"].(string)
	tone, _ := params["tone"].(string)
	if topic == "" {
		topic = extractDocTopic(original) // handlers_doc_auto_shared.go 의 헬퍼
	}
	if topic == "" {
		topic = "보고서"
	}
	if tone == "" {
		tone = "formal"
	}

	// LLM 프롬프트 — PDF용 구조화된 본문
	sysPrompt := ""
	if lang == "en" {
		sysPrompt = `You write professional PDF document content. Output structured plain text.

Structure:
- Line 1: TITLE (uppercase or title case)
- Line 2: (subtitle/date) optional
- Empty line
- Then sections separated by "==" headers:
  == Section Name ==
  Section body...

Length: 400~800 words, 4~6 sections.
Tone: %s
Topic should be practical. Realistic example numbers/dates.
NO markdown (# ** etc). Plain text + == headers only.
IMPORTANT: Note this is sample template — replace with real data.`
		sysPrompt = fmt.Sprintf(sysPrompt, tone)
	} else {
		sysPrompt = fmt.Sprintf(`당신은 PDF 문서 작성 비서입니다. 구조화된 일반 텍스트를 출력하세요.

구조:
- 1줄: 제목
- 2줄: (부제/날짜) 선택
- 빈 줄
- 그 다음 섹션들을 "==" 헤더로 구분:
  == 섹션 이름 ==
  섹션 본문...

길이: 400~800단어, 4~6섹션
어조: %s ("formal"=정중, "casual"=친근)
실용적이고 구체적인 예시/숫자 포함.
마크다운 금지 (# ** 등). 일반 텍스트 + == 헤더만.
중요: 가상 샘플 데이터입니다. 실제 데이터로 교체 사용.`, tone)
	}

	content, _, err := callGroqWithFallback([]groqMsg{
		{Role: "system", Content: sysPrompt},
		{Role: "user", Content: "주제: " + topic},
	}, 2500, false)
	if err != nil || content == "" {
		return map[string]any{"success": false, "error": "LLM 호출 실패"},
			fmt.Sprintf("PDF 생성 실패: %v", err)
	}

	// PDF 생성 (gofpdf + 한글 UTF-8 폰트 임베딩)
	pdf := gofpdf.New("P", "mm", "A4", "")

	// NanumGothic 임베딩 — 한글/영문 모두 표시
	// 폰트 파일: backend/fonts/NanumGothic.ttf (Tauri 리소스 또는 실행 디렉토리)
	fontPath := findFontPath("NanumGothic.ttf")
	useKoreanFont := false
	if fontPath != "" {
		pdf.AddUTF8Font("NG", "", fontPath)
		useKoreanFont = true
	}
	pdf.AddPage()
	if useKoreanFont {
		pdf.SetFont("NG", "", 20)
	} else {
		pdf.SetFont("Arial", "B", 20)
	}

	// 제목 (첫 줄)
	lines := strings.Split(content, "\n")
	title := topic
	if len(lines) > 0 && lines[0] != "" {
		title = strings.TrimSpace(lines[0])
	}
	pdf.CellFormat(0, 10, transliterate(title), "", 1, "C", false, 0, "")
	pdf.Ln(4)

	// 메타: 자동 생성 안내
	if useKoreanFont {
		pdf.SetFont("NG", "", 9)
	} else {
		pdf.SetFont("Arial", "I", 9)
	}
	pdf.SetTextColor(120, 120, 120)
	metaText := fmt.Sprintf("Auto-generated by Nexus AI · %s · Sample Template", time.Now().Format("2006-01-02 15:04"))
	if lang == "ko" {
		metaText = fmt.Sprintf("Nexus AI 자동 생성 · %s · 가상 샘플 데이터", time.Now().Format("2006-01-02 15:04"))
	}
	pdf.CellFormat(0, 6, transliterate(metaText), "", 1, "C", false, 0, "")
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(8)

	// 본문
	bodyStart := 1
	if len(lines) > 1 && strings.TrimSpace(lines[1]) != "" && !strings.HasPrefix(strings.TrimSpace(lines[1]), "==") {
		// 부제
		if useKoreanFont {
			pdf.SetFont("NG", "", 11)
		} else {
			pdf.SetFont("Arial", "I", 11)
		}
		pdf.SetTextColor(80, 80, 80)
		pdf.CellFormat(0, 6, transliterate(strings.TrimSpace(lines[1])), "", 1, "C", false, 0, "")
		pdf.SetTextColor(0, 0, 0)
		pdf.Ln(6)
		bodyStart = 2
	}

	if useKoreanFont {
		pdf.SetFont("NG", "", 11)
	} else {
		pdf.SetFont("Arial", "", 11)
	}
	for i := bodyStart; i < len(lines); i++ {
		line := strings.TrimSpace(lines[i])
		if line == "" {
			pdf.Ln(3)
			continue
		}
		// == Section Header ==
		if strings.HasPrefix(line, "==") && strings.HasSuffix(line, "==") {
			pdf.Ln(2)
			if useKoreanFont {
				pdf.SetFont("NG", "", 13)
			} else {
				pdf.SetFont("Arial", "B", 13)
			}
			pdf.SetTextColor(30, 64, 175) // blue accent
			pdf.CellFormat(0, 8, transliterate(strings.TrimSpace(strings.Trim(line, "="))), "", 1, "L", false, 0, "")
			pdf.SetTextColor(0, 0, 0)
			if useKoreanFont {
				pdf.SetFont("NG", "", 11)
			} else {
				pdf.SetFont("Arial", "", 11)
			}
			pdf.Ln(1)
			continue
		}
		// 일반 본문 (자동 줄바꿈)
		pdf.MultiCell(0, 6, transliterate(line), "", "L", false)
		pdf.Ln(1)
	}

	// 푸터
	pdf.SetY(-20)
	pdf.SetFont("Arial", "I", 8)
	pdf.SetTextColor(150, 150, 150)
	pdf.CellFormat(0, 5, "Nexus AI · Page "+fmt.Sprintf("%d", pdf.PageNo()), "", 0, "C", false, 0, "")

	// 저장
	safeTitle := sanitizeDocAutoFilename(topic)
	filename := fmt.Sprintf("%s_%s.pdf", safeTitle, time.Now().Format("20060102_150405"))
	home, _ := os.UserHomeDir()
	savePath := filepath.Join(home, "Desktop", filename)
	if err := pdf.OutputFileAndClose(savePath); err != nil {
		return map[string]any{"success": false, "error": err.Error()},
			fmt.Sprintf("PDF 저장 실패: %v", err)
	}

	info, _ := os.Stat(savePath)
	sizeKB := float64(0)
	if info != nil {
		sizeKB = float64(info.Size()) / 1024
	}

	pages := pdf.PageCount()
	chars := len([]rune(content))
	msg := fmt.Sprintf("✅ PDF 저장 완료 (가상 샘플): %s (%d페이지, %.1fKB) — 바탕화면", filename, pages, sizeKB)
	if lang == "en" {
		msg = fmt.Sprintf("✅ PDF saved (sample template): %s (%d pages, %.1fKB) — Desktop", filename, pages, sizeKB)
	}

	return map[string]any{
		"success":     true,
		"fileName":    filename,
		"path":        savePath,
		"url":         "file:///" + filepath.ToSlash(savePath),
		"mimeType":    "application/pdf",
		"format":      "pdf",
		"pages":       pages,
		"chars":       chars,
		"size_kb":     sizeKB,
		"operation":   "pdf_create",
		"topic":       topic,
		"is_sample":   true,
		"sample_note": sampleNote(lang),
	}, msg
}

// transliterate: 한국어/특수문자 → ASCII 유사 대체 (gofpdf 기본 폰트 한계)
// 한국어 문자는 그대로 두지만 일부 특수문자만 정리 (PDF 깨짐 방지)
// 진짜 한글 PDF 는 TTF 폰트 임베딩 필요 (다음 라운드)
func transliterate(s string) string {
	// CP1252 호환 문자만 통과시키도록 보수적 처리
	// 한글은 PDF 에서 깨질 수 있지만 영문은 깔끔
	replacements := map[string]string{
		"‘": "'", "’": "'", // smart quotes
		"“": "\"", "”": "\"",
		"–": "-", "—": "--", // dashes
		"…": "...",
		"·": "·",
	}
	for from, to := range replacements {
		s = strings.ReplaceAll(s, from, to)
	}
	return s
}

// findFontPath: 폰트 파일 탐색 (실행 디렉토리 / Tauri 리소스 / 절대 경로)
func findFontPath(name string) string {
	candidates := []string{
		"fonts/" + name,                                // backend/fonts/
		"./fonts/" + name,
		"./" + name,
		"./backend/fonts/" + name,
		"./resources/fonts/" + name,                   // Tauri resource path
		filepath.Join(os.Getenv("APPDATA"), "Nexus", "fonts", name),
	}
	// 실행 파일 디렉토리
	if exe, err := os.Executable(); err == nil {
		dir := filepath.Dir(exe)
		candidates = append(candidates,
			filepath.Join(dir, "fonts", name),
			filepath.Join(dir, name),
			filepath.Join(dir, "resources", "fonts", name),
		)
	}
	for _, p := range candidates {
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	return ""
}
