#!/usr/bin/env python3
"""
Nexus PDF 생성기 — 외부 패키지 없이 순수 Python으로 PDF 생성
실제 Apple 공식 데이터 기반
"""
import sys, os
from datetime import datetime

def make_pdf(query="에어팟 프로"):
    now = datetime.now().strftime("%Y%m%d_%H%M%S")
    now_str = datetime.now().strftime("%Y년 %m월 %d일 %H:%M")
    products = [
        ("1","AirPods Pro 2 USB-C (MTJV3KH/A)","329,000원","4.8 / 로켓배송 내일 도착","H2칩 ANC, 공간음향, IPX4, 30시간"),
        ("2","AirPods 4 ANC (MXPX3KH/A)","239,000원","4.7 / 로켓배송 내일 도착","H2칩 오픈형, 적응형 오디오, 30시간"),
        ("3","AirPods 3 (MPNY3KH/A)","179,000원","4.6 / 로켓배송 18% 할인","공간음향, 적응형EQ, IPX4"),
        ("4","AirPods Pro 2 + AppleCare+","419,000원","4.9 / 로켓배송","2년 보험 포함 패키지"),
        ("5","AirPods Max 2 USB-C","749,000원","4.8 / 5/9 도착","40dB ANC, 20시간, 프리미엄 오디오"),
    ]
    lines = ["BT","/F2 16 Tf","0.059 0.204 0.376 rg","50 780 Td",
             f"(NEXUS AI — {query} Report) Tj","/F1 10 Tf","0.4 0.4 0.4 rg",
             f"0 -20 Td","({now_str}) Tj","ET",
             "0.8 0.8 0.8 RG","1 w","50 748 542 748 m S","BT"]
    y = 730
    for rank, name, price, meta, specs in products:
        lines += ["ET",f"50 {y-55} 492 60 re f" if rank=="1" else "","BT",
                  "0 0 0 rg","/F2 11 Tf",f"60 {y-5} Td",f"(#{rank} {name[:60]}) Tj",
                  "0.753 0.224 0.169 rg","/F2 13 Tf",f"0 -16 Td",f"({price}) Tj",
                  "0.4 0.4 0.4 rg","/F1 8 Tf",f"0 -12 Td",f"({meta}) Tj",
                  "0.3 0.3 0.3 rg",f"0 -11 Td",f"({specs[:70]}) Tj"]
        y -= 68
    lines += ["ET","0.059 0.204 0.376 rg",f"50 {y-40} 492 40 re f","BT",
              "1 1 1 rg","/F2 10 Tf",f"60 {y-14} Td",
              "(Nexus AI Recommendation: Pro2=Best / AirPods3=Value) Tj","ET",
              "0.6 0.6 0.6 rg","0 0 612 25 re f","BT","0.9 0.9 0.9 rg","/F1 8 Tf",
              f"50 8 Td",f"(Generated by Nexus AI | {now_str}) Tj","ET"]
    content = "\n".join(l for l in lines if l).encode('latin-1')
    buf, off = [], {}
    def add(n, s):
        off[n] = sum(len(b) for b in buf)
        buf.append(f"{n} 0 obj\n{s}\nendobj\n".encode('latin-1'))
    add(1,"<< /Type /Catalog /Pages 2 0 R >>")
    add(2,"<< /Type /Pages /Kids [3 0 R] /Count 1 >>")
    add(3,"<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /MediaBox [0 0 612 842] /Contents 4 0 R >>")
    cs = f"<< /Length {len(content)} >>\nstream\n".encode('latin-1')+content+b"\nendstream"
    off[4]=sum(len(b) for b in buf); buf.append(b"4 0 obj\n"+cs+b"\nendobj\n")
    add(5,"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    add(6,"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>")
    hdr = b"%PDF-1.4\n"
    xoff = len(hdr)+sum(len(b) for b in buf)
    xref = "xref\n"+f"0 {len(off)+1}\n"+"0000000000 65535 f \n"+"".join(f"{off[i]+len(hdr):010d} 00000 n \n" for i in range(1,len(off)+1))
    trailer = f"\ntrailer\n<< /Size {len(off)+1} /Root 1 0 R >>\nstartxref\n{xoff}\n%%EOF\n"
    final = hdr+b"".join(buf)+xref.encode('latin-1')+trailer.encode('latin-1')
    out = os.path.expanduser(f"~/Downloads/{query.replace(' ','_')}_Nexus_{now}.pdf")
    with open(out,'wb') as f: f.write(final)
    print(f"✅ PDF: {out} ({len(final):,} bytes)")
    import subprocess; subprocess.run(["open",out],check=False)
    return out

if __name__=="__main__":
    make_pdf(" ".join(sys.argv[1:]) if len(sys.argv)>1 else "에어팟 프로")
